### ISSUE TITLE
`npm start` path error on Unix

### ISSUE THREAD

**Issue by drauschenbach** [Colored-Coins/coloredcoinsd#7]
Cannot run `npm start` on Mac due to strange use of backslashes in `package.json`.

```bash
$ npm start

> colordcoinsd@0.0.1 start /Users/davidr/workspaces/coloredcoinsd
> node .\server.js

module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/davidr/workspaces/coloredcoinsd/.server.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by oleiba** [comment]
PR accepted #8
